/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dammne (https://sketchfab.com/dammne)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chibi-ufo-low-poly-26fc3ada37264aa482b02e3d38ed1ba6
title: Chibi UFO - Low Poly
*/

import * as THREE from "three";
import { useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(
    { mesh }: any,
    props: JSX.IntrinsicElements["group"]
) {
    const { nodes, materials } = useGLTF("/models/ufo/scene.gltf") as any;
    const [hovered, setHover] = useState(false);

    useFrame(() => {
        if (!mesh.current) return;
        mesh.current.scale.x = THREE.MathUtils.lerp(
            mesh.current.scale.x,
            hovered ? 0.0034 : 0.003,
            0.1
        );
        mesh.current.scale.y = THREE.MathUtils.lerp(
            mesh.current.scale.y,
            hovered ? 0.0034 : 0.003,
            0.1
        );
        mesh.current.scale.z = THREE.MathUtils.lerp(
            mesh.current.scale.z,
            hovered ? 0.0034 : 0.003,
            0.1
        );
    });

    return (
        <group
            onPointerOver={() => setHover(true)}
            onPointerOut={() => setHover(false)}
            ref={mesh}
            {...props}
            dispose={null}
            scale={[0.002, 0.002, 0.002]}
        >
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <group name="UFO">
                        <group position={[0, 56.13, -131.34]}>
                            <mesh
                                geometry={nodes.Cylinder_NEON_0.geometry}
                                material={nodes.Cylinder_NEON_0.material}
                            />
                        </group>
                        <group
                            position={[113.75, 56.13, -65.67]}
                            rotation={[0, -Math.PI / 3, 0]}
                        >
                            <mesh
                                geometry={nodes.Cylinder_2_NEON_0.geometry}
                                material={nodes.Cylinder_2_NEON_0.material}
                            />
                        </group>
                        <group
                            position={[113.75, 56.13, 65.67]}
                            rotation={[Math.PI, -Math.PI / 3, Math.PI]}
                        >
                            <mesh
                                geometry={nodes.Cylinder_3_NEON_0.geometry}
                                material={nodes.Cylinder_3_NEON_0.material}
                            />
                        </group>
                        <group
                            position={[0, 56.13, 131.34]}
                            rotation={[Math.PI, 0, Math.PI]}
                        >
                            <mesh
                                geometry={nodes.Cylinder_4_NEON_0.geometry}
                                material={nodes.Cylinder_4_NEON_0.material}
                            />
                        </group>
                        <group
                            position={[-113.75, 56.13, 65.67]}
                            rotation={[Math.PI, Math.PI / 3, -Math.PI]}
                        >
                            <mesh
                                geometry={nodes.Cylinder_5_NEON_0.geometry}
                                material={nodes.Cylinder_5_NEON_0.material}
                            />
                        </group>
                        <group
                            position={[-113.75, 56.13, -65.67]}
                            rotation={[0, Math.PI / 3, 0]}
                        >
                            <mesh
                                geometry={nodes.Cylinder_6_NEON_0.geometry}
                                material={nodes.Cylinder_6_NEON_0.material}
                            />
                        </group>
                        <group position={[0, 17.68, 0]}>
                            <group position={[0, 0, -190]}>
                                <mesh
                                    geometry={nodes.Sphere_13_METAL_0.geometry}
                                    material={nodes.Sphere_13_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[88.3, 0, -168.24]}
                                rotation={[0, -0.48, 0]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_12_METAL_0.geometry}
                                    material={nodes.Sphere_12_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[156.37, 0, -107.93]}
                                rotation={[0, -0.97, 0]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_11_METAL_0.geometry}
                                    material={nodes.Sphere_11_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[188.61, 0, -22.9]}
                                rotation={[0, -1.45, 0]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_10_METAL_0.geometry}
                                    material={nodes.Sphere_10_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[177.65, 0, 67.37]}
                                rotation={[Math.PI, -1.21, Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_9_METAL_0.geometry}
                                    material={nodes.Sphere_9_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[125.99, 0, 142.22]}
                                rotation={[Math.PI, -0.72, Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_8_METAL_0.geometry}
                                    material={nodes.Sphere_8_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[45.47, 0, 184.48]}
                                rotation={[Math.PI, -0.24, Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_7_METAL_0.geometry}
                                    material={nodes.Sphere_7_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-45.47, 0, 184.48]}
                                rotation={[Math.PI, 0.24, -Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_6_METAL_0.geometry}
                                    material={nodes.Sphere_6_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-125.99, 0, 142.22]}
                                rotation={[Math.PI, 0.72, -Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_5_METAL_0.geometry}
                                    material={nodes.Sphere_5_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-177.65, 0, 67.37]}
                                rotation={[Math.PI, 1.21, -Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_4_METAL_0.geometry}
                                    material={nodes.Sphere_4_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-188.61, 0, -22.9]}
                                rotation={[0, 1.45, 0]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_3_METAL_0.geometry}
                                    material={nodes.Sphere_3_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-156.37, 0, -107.93]}
                                rotation={[0, 0.97, 0]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_2_METAL_0.geometry}
                                    material={nodes.Sphere_2_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-88.3, 0, -168.24]}
                                rotation={[0, 0.48, 0]}
                            >
                                <mesh
                                    geometry={nodes.Sphere_1_METAL_0.geometry}
                                    material={nodes.Sphere_1_METAL_0.material}
                                />
                            </group>
                        </group>
                        <group position={[0, 56.13, 0]}>
                            <group position={[0, 0, -136]}>
                                <mesh
                                    geometry={nodes.Tube_1_0_METAL_0.geometry}
                                    material={nodes.Tube_1_0_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[117.78, 0, -68]}
                                rotation={[0, -Math.PI / 3, 0]}
                            >
                                <mesh
                                    geometry={nodes.Tube_1_1_METAL_0.geometry}
                                    material={nodes.Tube_1_1_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[117.78, 0, 68]}
                                rotation={[Math.PI, -Math.PI / 3, Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Tube_1_2_METAL_0.geometry}
                                    material={nodes.Tube_1_2_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[0, 0, 136]}
                                rotation={[Math.PI, 0, Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Tube_1_3_METAL_0.geometry}
                                    material={nodes.Tube_1_3_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-117.78, 0, 68]}
                                rotation={[Math.PI, Math.PI / 3, -Math.PI]}
                            >
                                <mesh
                                    geometry={nodes.Tube_1_4_METAL_0.geometry}
                                    material={nodes.Tube_1_4_METAL_0.material}
                                />
                            </group>
                            <group
                                position={[-117.78, 0, -68]}
                                rotation={[0, Math.PI / 3, 0]}
                            >
                                <mesh
                                    geometry={nodes.Tube_1_5_METAL_0.geometry}
                                    material={nodes.Tube_1_5_METAL_0.material}
                                />
                            </group>
                        </group>
                        <group position={[0, 2.41, 0]}>
                            <group position={[0, 39.18, 0]}>
                                <mesh
                                    geometry={nodes.Cap_1_BODY_0.geometry}
                                    material={nodes.Cap_1_BODY_0.material}
                                />
                            </group>
                            <group position={[0, -48.95, 0]}>
                                <mesh
                                    geometry={nodes.Cap_2_BODY_0.geometry}
                                    material={nodes.Cap_2_BODY_0.material}
                                />
                            </group>
                            <mesh
                                geometry={nodes.Loft_BODY_0.geometry}
                                material={nodes.Loft_BODY_0.material}
                            />
                        </group>
                        <mesh
                            geometry={nodes.Sphere_NEON_0.geometry}
                            material={nodes.Sphere_NEON_0.material}
                        />
                        <group position={[0, 107.59, 0]}>
                            <mesh
                                geometry={nodes.Capsule_GLASS_0.geometry}
                                material={nodes.Capsule_GLASS_0.material}
                            />
                        </group>
                        <group position={[0, 107.59, 0]}>
                            <mesh
                                geometry={nodes.Capsule_2_GLASS_0.geometry}
                                material={nodes.Capsule_2_GLASS_0.material}
                            />
                        </group>
                        <group position={[0, 56.26, 0]}>
                            <mesh
                                geometry={nodes.Tube_CABIN_0.geometry}
                                material={materials.CABIN}
                            />
                        </group>
                    </group>
                    <group
                        position={[-199.03, 77.58, 319.35]}
                        rotation={[0, 0.97, 0.02]}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/models/ufo/scene.gltf");
